<html>
<meta charset="utf-8">
<head>
<title>РГТЭУ Кемеровсктй институт</title>
<meta http-equiv="Content-Type” content="text/html; charset=windows=1251">
<META name="Author™ content="http://ailus.ru"><meta name="Copyright" content="http://ailus.ru">
</head>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" rightmargin="0" bottommargin="0" bgcolor="#ffffff">
<link href="images/index.ccs" type="text/css" rel="stylesheet"
<table border=1 width=100% height=20%>
<td width=100% height=20% align=center> Лабораторные работы по курсу "Разработка интернет приложений в сфере коммерции посредством PHP и MySQl" <br>Студента группы ПИс-181: Баяновой Ульяны Сергеевны <br> Проверил: Киринберг А.Г.</td>
</table>

<table border=1 width=100% height=70%>

<td width=30% height=70% align=center> 
<a href="orderform.php"> Первая лабораторная работа </a>
<br><br>
<a href="orderform_2.php"> Вторая лабораторная работа </a>
<br><br>
<a href="orderform_3.php"> Третья лабораторная работа </a>
<br><br>
<a href="orderform_4.php"> Четвертая лабораторная работа </a>
<br><br>
<a href="orderform_5.php"> Пятая лабораторная работа </a>

</td>
<td width=70% height=70% align=center>